POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Way2",
    "name": "Walt Disney",
    "body": "The way to get started is to quit talking and begin doing"
}

###
GET http://localhost:3000/posts/abracadabra
Content-Type: application/json

{}

###
GET http://localhost:3000/posts/61decabb8f41aa3c9f58ccc5
Content-Type: application/json

{}